var api = {
    getMenu: '../api/get_menu',
    getPublic: '../api/get_public',
    login: '../api/login',
    getWaitShip: '../api/get_waitShip',
    getAfterSaleNumber:'../api/get_afterSaleNumber',
    updateGoodsState: '../api/update_goodsState',
    getGoods: '../api/get_goods',
    getCategory: '../api/get_category',
    addCategory: '../api/add_category',
    delCategory: '../api/del_category',
    updateGoodsCategory: '../api/update_goods_category',
    updateGoodsPrice: '../api/update_goods_price',
    addGoods: '../api/add_goods',
    addSpecification: '../api/add_specification',
    getSpecification: '../api/get_specification',
    getBrand: '../api/get_brand',
    updateBrandState: '../api/update_brandState',
    addBrand: '../api/add_brand',
    updateBrand: '../api/update_brand',
    getParam: '../api/get_param',
    updateGoods: '../api/update_goods',
    order: '../api/order',
    getOrderBySearch: '../api/get_order_by_search',
    addLogisticsCodeToOrder: '../api/add_logistics_code_to_order', // 物流信息 阿里
    updateOrderState: '../api/update_orderState',
    getAd: '../api/get_ad',
    updateAdState: '../api/update_adState',
    delAd: '../api/del_ad',
    getGoodsByCategory: '../api/get_goods_by_category',
    addAd: '../api/add_ad',
    editAd: '../api/edit_ad',
    getNavigation: '../api/get_navigation',
    updateNavigation: '../api/update_navigation',
    getWaterfall: '../api/get_waterfall',
    updateWaterfall: '../api/update_waterfall',
    getPosition: '../api/get_position',
    getAccount: '../api/get_account',
    addAccount: '../api/add_account',
    getUser: '../api/get_user',
    delReview: '../api/del_review',
    updateReview: '../api/update_review',
    updateBestReview: '../api/update_best_review',
    getReview: '../api/get_review',
}